# 부트를 쓰기 때문에 있는 설정공간

spring:
  profiles:
    active:
      - dev
  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 400MB
#      file-size-threshold: 10MB
# server:
#   port: 80
